FROM docker.io/library/python:3.11-alpine

RUN /usr/local/bin/pip3 install --upgrade click Jinja2 pycryptodome

COPY ./compiler.py /compiler.py
COPY ./authorized_mpsks.j2 /authorized_mpsks.j2
COPY ./authorized_users.j2 /authorized_users.j2

ENTRYPOINT ["/usr/local/bin/python3", "/compiler.py"]
